### ISSUE TITLE
Help with automation: understanding how schema's and presets work

### ISSUE THREAD

**Issue by unreal4u** [plugwise/Plugwise-Smile#113]
Hi! 

First of all: excellent work guys! I bought Smile+Anna recently and your integration works as a charm! Kudos to you!!

That being said, I need some help with setting up an automation. I have 2 automations at home, one for when I leave and the other for when I arrive.

When I go out, I tell it to set the 'away' preset_mode: 

```
- id: '1612911872117'
  alias: Set climate "away" when people are not present
  description: ''
  trigger:
  - platform: mqtt
    topic: sensors/whoishome/peoplepresent
    payload: 'no'
  condition: []
  action:
  - service: climate.set_preset_mode
    data:
      preset_mode: away
      entity_id: climate.anna
  mode: single
```

However, if I understand it correctly, the schema will still run in the background right? Say I have a schema that looks like follows:

22:00 - asleep
09:00 - home

What if I leave the house at 08:00 and don't come back until 17:00? If I send the above command at 08:00, will Smile still activate the 'home' protocol at 09:00?

And if sending the command above disables the schema: is there a way to tell Smile to enable it back as soon as I come home? Like, if I come home at 23:00 I don't want to enable the 'home' preset, but let Smile decide what to do based on my schema.

The more I think about it, the more I am inclined to implement this directly in either Home Assistant or NodeRed. However, I would like to fallback to the schema just in case Home Assistant crashes and stops sending commands or whatnot. It would also make a vacation schema more difficult to implement.

Sorry if this doesn't belong here, in that case just tell me and I'll post it where it should!

Greetings.
